'use client'

import { useEffect, useMemo, useState } from 'react'
import { jsPDF } from 'jspdf'
import { supabase } from '../../../lib/supabase'
import { blobToDataUrl, getLocalFile } from '../../../lib/crmLocalFiles'

const UPLOAD_STORAGE_KEY = 'signal-crm-upload-files'

const REPORT_TYPES = [
  { id: 'summary', title: '고객 요약 리포트', desc: '고객 기본정보와 상담 요약을 1페이지로 정리' },
  { id: 'coverage', title: '담보 상세 리포트', desc: '월 보험료, 보험 건수, 부족 태그 중심 정리' },
  { id: 'claim', title: '상담 준비 리포트', desc: '현재 상태와 다음 상담 포인트 정리' },
  { id: 'family', title: '가족 전체 리포트', desc: '가족 인원과 가족 관리 포인트 정리' },
]

export default function ReportsPage() {
  const [customers, setCustomers] = useState<any[]>([])
  const [materials, setMaterials] = useState<any[]>([])
  const [selectedCustomerId, setSelectedCustomerId] = useState('')
  const [selectedType, setSelectedType] = useState('summary')
  const [loading, setLoading] = useState(true)
  const [history, setHistory] = useState<{ customer: string; type: string; date: string }[]>([])

  useEffect(() => {
    const load = async () => {
      const { data: { session } } = await supabase.auth.getSession()
      if (!session) {
        setLoading(false)
        return
      }
      const { data } = await supabase
        .from('customers')
        .select('*')
        .eq('advisor_id', session.user.id)
        .order('name', { ascending: true })
      const list = data || []
      setCustomers(list)
      setSelectedCustomerId(list[0]?.id || '')
      try {
        const saved = window.localStorage.getItem(UPLOAD_STORAGE_KEY)
        if (saved) setMaterials(JSON.parse(saved))
      } catch {}
      setLoading(false)
    }
    load()
  }, [])

  const selectedCustomer = useMemo(() => (
    customers.find((customer) => customer.id === selectedCustomerId)
  ), [customers, selectedCustomerId])

  const selectedReport = REPORT_TYPES.find((item) => item.id === selectedType) || REPORT_TYPES[0]
  const reportMaterials = useMemo(() => (
    materials.filter((item) => item.customerId === selectedCustomerId && item.includeInReport !== false)
  ), [materials, selectedCustomerId])

  const downloadPdf = () => {
    if (!selectedCustomer) return

    const doc = new jsPDF()
    const today = new Date().toLocaleDateString('ko-KR')
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(18)
    doc.text('Signal CRM Report', 20, 24)
    doc.setFontSize(12)
    doc.text(selectedReport.title, 20, 34)

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    const rows = [
      ['Customer', selectedCustomer.name || '-'],
      ['Phone', selectedCustomer.phone || '-'],
      ['Status', selectedCustomer.status || '-'],
      ['Monthly Premium', `${Number(selectedCustomer.monthly_premium || 0).toLocaleString()} KRW`],
      ['Policy Count', `${selectedCustomer.policy_count || 0}`],
      ['Join Date', selectedCustomer.join_date || '-'],
      ['Tags', Array.isArray(selectedCustomer.tags) ? selectedCustomer.tags.join(', ') : '-'],
      ['Summary', selectedCustomer.consulting_summary || '-'],
      ['Materials', reportMaterials.map((item) => `${item.category}:${item.name}`).join(' / ') || '-'],
    ]

    let y = 48
    rows.forEach(([label, value]) => {
      doc.setFont('helvetica', 'bold')
      doc.text(label, 20, y)
      doc.setFont('helvetica', 'normal')
      doc.text(String(value).slice(0, 80), 68, y)
      y += 10
    })

    doc.setDrawColor(226, 232, 240)
    doc.line(20, y + 2, 190, y + 2)
    doc.setFontSize(9)
    doc.text(`Generated by Signal CRM · ${today}`, 20, y + 12)
    doc.save(`signal-crm-${selectedCustomer.name || 'customer'}-${selectedType}.pdf`)

    setHistory((prev) => [
      { customer: selectedCustomer.name, type: selectedReport.title, date: today },
      ...prev.slice(0, 4),
    ])
  }

  const openPrintReport = async () => {
    if (!selectedCustomer) return
    const today = new Date().toLocaleDateString('ko-KR')
    const materialsWithImages = await Promise.all(reportMaterials.map(async (item) => {
      const localFile = item.hasLocalFile ? await getLocalFile(item.id) : null
      const imageDataUrl = localFile?.type?.startsWith('image/') ? await blobToDataUrl(localFile.blob) : ''
      return { ...item, imageDataUrl }
    }))
    const materialRows = materialsWithImages.length > 0
      ? materialsWithImages.map((item) => `
        <tr>
          <td>${escapeHtml(item.category || '-')}</td>
          <td>
            ${item.imageDataUrl ? `<img src="${item.imageDataUrl}" class="thumb" alt="" />` : ''}
            <div>${escapeHtml(item.name || '-')}</div>
          </td>
          <td>${escapeHtml(item.memo || '-')}</td>
          <td>${item.driveUrl ? `<a href="${escapeAttribute(item.driveUrl)}" target="_blank">Drive 열기</a>` : '-'}</td>
        </tr>
      `).join('')
      : '<tr><td colspan="4" class="empty">연결된 자료가 없습니다.</td></tr>'

    const html = `<!doctype html>
      <html lang="ko">
      <head>
        <meta charset="utf-8" />
        <title>${escapeHtml(selectedCustomer.name || '고객')} 리포트</title>
        <style>
          body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","Noto Sans KR",sans-serif;margin:0;background:#f1f5f9;color:#0f172a}
          .page{max-width:900px;margin:28px auto;background:#fff;padding:36px;border-radius:18px;border:1px solid #e2e8f0}
          h1{font-size:26px;margin:0 0 6px;color:#1a3a6e} h2{font-size:15px;margin:28px 0 12px;color:#0f172a}
          .sub{color:#64748b;font-size:13px;margin-bottom:22px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}
          .box{background:#f8fafc;border:1px solid #e8edf3;border-radius:12px;padding:13px}.label{font-size:11px;color:#64748b;margin-bottom:4px}.val{font-size:14px;font-weight:700}
          table{width:100%;border-collapse:collapse}th,td{text-align:left;border-bottom:1px solid #e8edf3;padding:10px;font-size:12px;vertical-align:top}th{background:#f8fafc;color:#64748b}
          .thumb{width:120px;height:80px;object-fit:cover;border-radius:10px;border:1px solid #e2e8f0;margin-bottom:6px;display:block}
          .empty{text-align:center;color:#94a3b8}.actions{display:flex;justify-content:flex-end;margin-bottom:14px}.btn{border:none;background:#2563eb;color:white;border-radius:10px;padding:10px 16px;font-weight:700;cursor:pointer}
          @media print{body{background:#fff}.page{margin:0;max-width:none;border:none;border-radius:0}.actions{display:none}}
        </style>
      </head>
      <body>
        <div class="page">
          <div class="actions"><button class="btn" onclick="window.print()">PDF로 저장 / 인쇄</button></div>
          <h1>${escapeHtml(selectedReport.title)}</h1>
          <div class="sub">시그널 고객관리 · ${today}</div>
          <div class="grid">
            <Info label="고객명" value="${escapeAttribute(selectedCustomer.name || '-')}" />
            <Info label="연락처" value="${escapeAttribute(selectedCustomer.phone || '-')}" />
            <Info label="상태" value="${escapeAttribute(selectedCustomer.status || '-')}" />
            <Info label="월 보험료" value="${escapeAttribute(`${Number(selectedCustomer.monthly_premium || 0).toLocaleString()}원`)}" />
            <Info label="보험 건수" value="${escapeAttribute(`${selectedCustomer.policy_count || 0}건`)}" />
            <Info label="등록일" value="${escapeAttribute(selectedCustomer.join_date || '-')}" />
          </div>
          <h2>상담 요약</h2>
          <div class="box">${escapeHtml(selectedCustomer.consulting_summary || '상담 요약이 없습니다.')}</div>
          <h2>리포트 포함 자료</h2>
          <table>
            <thead><tr><th>구분</th><th>자료명</th><th>메모</th><th>링크</th></tr></thead>
            <tbody>${materialRows}</tbody>
          </table>
        </div>
      </body>
      </html>`.replace(/<Info label="([^"]*)" value="([^"]*)" \/>/g, '<div class="box"><div class="label">$1</div><div class="val">$2</div></div>')

    const reportWindow = window.open('', '_blank', 'noopener,noreferrer')
    if (!reportWindow) return
    reportWindow.document.write(html)
    reportWindow.document.close()
  }

  return (
    <>
      <div className="page-header">
        <div>
          <div className="page-title">PDF 리포트</div>
          <div className="page-subtitle">고객별 상담 리포트를 생성하고 다운로드합니다.</div>
        </div>
      </div>

      {loading ? (
        <div className="card card-p" style={{ padding: 80, textAlign: 'center', color: '#94a3b8' }}>불러오는 중...</div>
      ) : (
        <div className="grid-3">
          <div className="card card-p">
            <div className="card-title">고객 선택</div>
            <div className="flex-col gap-8" style={{ maxHeight: 420, overflowY: 'auto' }}>
              {customers.map((customer) => (
                <button
                  key={customer.id}
                  className={`dm-card${selectedCustomerId === customer.id ? ' active' : ''}`}
                  onClick={() => setSelectedCustomerId(customer.id)}
                  style={{ textAlign: 'left', padding: 12, background: selectedCustomerId === customer.id ? '#eff6ff' : '#fff' }}
                >
                  <div className="flex items-center gap-8">
                    <div className="profile-avatar">{customer.name?.slice(0, 1)}</div>
                    <div>
                      <div className="fw-700" style={{ fontSize: 13 }}>{customer.name}</div>
                      <div className="text-muted" style={{ fontSize: 11 }}>{Number(customer.monthly_premium || 0).toLocaleString()}원/월 · {customer.policy_count || 0}건</div>
                    </div>
                  </div>
                </button>
              ))}
              {customers.length === 0 && <div style={{ padding: 30, textAlign: 'center', color: '#94a3b8', fontSize: 12 }}>고객이 없습니다.</div>}
            </div>
          </div>

          <div className="card card-p">
            <div className="card-title">리포트 유형</div>
            <div className="flex-col gap-8">
              {REPORT_TYPES.map((item) => (
                <button key={item.id} className={`pdf-card${selectedType === item.id ? ' active' : ''}`} onClick={() => setSelectedType(item.id)}>
                  <span style={{ fontSize: 22 }}>📘</span>
                  <span style={{ textAlign: 'left' }}>
                    <span className="fw-700" style={{ display: 'block', fontSize: 13 }}>{item.title}</span>
                    <span className="text-muted" style={{ display: 'block', fontSize: 11, marginTop: 3 }}>{item.desc}</span>
                  </span>
                </button>
              ))}
            </div>
          </div>

          <div className="card card-p">
            <div className="card-title">리포트 생성</div>
            <div className="bg-gray rounded p-12 mb-16">
              <div className="text-muted" style={{ fontSize: 11, marginBottom: 4 }}>선택된 고객</div>
              <div className="fw-700" style={{ fontSize: 15 }}>{selectedCustomer?.name || '-'}</div>
              <div className="text-muted" style={{ fontSize: 11, marginTop: 12, marginBottom: 4 }}>선택된 리포트</div>
              <div className="fw-700" style={{ fontSize: 13 }}>{selectedReport.title}</div>
            </div>
            <button className="btn btn-primary" onClick={downloadPdf} disabled={!selectedCustomer} style={{ width: '100%', justifyContent: 'center', opacity: selectedCustomer ? 1 : 0.5 }}>
              PDF 다운로드
            </button>
            <button className="btn btn-secondary" onClick={openPrintReport} disabled={!selectedCustomer} style={{ width: '100%', justifyContent: 'center', marginTop: 8, opacity: selectedCustomer ? 1 : 0.5 }}>
              한글 리포트 열기
            </button>
            <div className="divider" />
            <div className="card-title">포함 자료</div>
            {reportMaterials.length === 0 ? (
              <div className="text-muted" style={{ fontSize: 12 }}>연결된 업로드 자료가 없습니다.</div>
            ) : (
              <div className="flex-col gap-8">
                {reportMaterials.map((item) => (
                  <div key={item.id} className="bg-gray rounded p-12">
                    <div className="fw-700" style={{ fontSize: 12 }}>{item.category} · {item.name}</div>
                    {item.memo && <div className="text-muted" style={{ fontSize: 11, marginTop: 3 }}>{item.memo}</div>}
                  </div>
                ))}
              </div>
            )}
            <div className="divider" />
            <div className="card-title">최근 생성 이력</div>
            {history.length === 0 ? (
              <div className="text-muted" style={{ fontSize: 12 }}>아직 생성한 리포트가 없습니다.</div>
            ) : (
              <div className="flex-col gap-8">
                {history.map((item, index) => (
                  <div key={`${item.customer}-${item.type}-${index}`} className="text-muted" style={{ fontSize: 12 }}>
                    {item.date} · {item.customer} · {item.type}
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      )}
    </>
  )
}

function escapeHtml(value: string) {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;')
}

function escapeAttribute(value: string) {
  return escapeHtml(value)
}
