// lib/insurance/data/surgery-db.ts
// 출처: KB 금쪽같은(별표11), 흥국생명 오튼튼(별표3), DB손해보험 약관
// 1~5종 수술 전체 항목 (88항 + 암수술 3항 + 방사선 2항)

import type { SurgeryItem } from '../types'

export const SURGERY_DB: SurgeryItem[] = [

  // ══════════════════════════════════════════════════
  // Ⅰ. 일반 질병 및 상해 치료목적의 수술
  // ══════════════════════════════════════════════════

  // ── 피부·유방 ──────────────────────────────────────
  {
    id: 's-001',
    item_no: '1',
    name: '피부이식수술 (25㎠ 이상), 피판수술',
    type: 3,
    category: 'skin_breast',
    is_cancer: false,
    kcd_codes: ['S00-T98', 'L00-L99'],
    synonyms: ['피부이식', '피판', '화상', 'skin graft', '피판분리', 'Z flap', 'W flap'],
    no_pay: ['피판분리수술', 'Z flap', 'W flap', '미용 목적 성형', '단순 봉합술'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
    notes: '피판분리수술, Z flap, W flap은 제외',
  },
  {
    id: 's-002',
    item_no: '2',
    name: '피부이식수술 (25㎠ 미만)',
    type: 1,
    category: 'skin_breast',
    is_cancer: false,
    kcd_codes: ['S00-T98', 'L00-L99'],
    synonyms: ['피부이식', '소면적', '화상'],
    no_pay: ['미용 목적', '단순 봉합'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-003',
    item_no: '3',
    name: '유방절단수술 (Mastectomy)',
    type: 3,
    category: 'skin_breast',
    is_cancer: false,
    kcd_codes: ['C50', 'N60-N64'],
    synonyms: ['유방절제', '유방암', '유방절단', 'mastectomy', '가슴', '유방재건'],
    no_pay: ['미용·축소 목적 유방수술', '지방흡입술(요양급여 해당 외)', '유방확대'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
    notes: '암 근치술은 5종(암수술 분류표) 별도 적용. 유방재건술은 유방암 환자에 한해 보상',
  },
  {
    id: 's-004',
    item_no: '4',
    name: '기타 유방수술 (농양의 절개·배액 제외)',
    type: 1,
    category: 'skin_breast',
    is_cancer: false,
    kcd_codes: ['N60-N64', 'D24'],
    synonyms: ['유방', '맘모토미', 'Mammotomy', '유방낭종', '유방종양'],
    no_pay: ['농양의 절개 및 배액', '미용 목적', '유방확대·축소'],
    is_disputed: true,
    sources: ['KB', '흥국생명', 'DB손해보험'],
    notes: '치료목적 Mammotomy: 수술개시일부터 60일 이내 2회 이상은 1회로 간주',
  },

  // ── 근골격 ────────────────────────────────────────
  {
    id: 's-005',
    item_no: '5',
    name: '골(骨) 이식수술',
    type: 2,
    category: 'musculoskeletal',
    is_cancer: false,
    kcd_codes: ['M86-M89', 'S00-T98'],
    synonyms: ['골이식', '뼈이식', '이식'],
    no_pay: ['단순 골절 고정술'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-006',
    item_no: '6',
    name: '두개골 관혈수술 (비골·비중격·상하악골·악관절 제외)',
    type: 3,
    category: 'musculoskeletal',
    is_cancer: false,
    kcd_codes: ['S02', 'M00-M99'],
    synonyms: ['두개골', '머리뼈', 'cranium', '두개'],
    no_pay: ['비골(코뼈) 수술 → 7번 항목', '상·하악골·악관절 → 8번 항목'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-007',
    item_no: '7',
    name: '비골(코뼈) 수술 (비중격 만곡증·수면무호흡 수술 제외)',
    type: 1,
    category: 'musculoskeletal',
    is_cancer: false,
    kcd_codes: ['J34.2', 'S02.2'],
    synonyms: ['코뼈', '비골', '코골절', '코'],
    no_pay: ['비중격 만곡증 수술', '수면무호흡 수술', '미용 코성형(융비술)'],
    is_disputed: true,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-008',
    item_no: '8',
    name: '상악골·하악골·악관절 관혈수술',
    type: 2,
    category: 'musculoskeletal',
    is_cancer: false,
    kcd_codes: ['K07', 'S02.4', 'S02.6'],
    synonyms: ['상악골', '하악골', '악관절', '위턱', '아래턱', '턱관절'],
    no_pay: ['치과 처치 및 수술에 수반하는 것', '임플란트'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-009',
    item_no: '9',
    name: '척추골·골반골·추간판 관혈수술',
    type: 3,
    category: 'musculoskeletal',
    is_cancer: false,
    kcd_codes: ['M40-M54', 'S12-S32'],
    synonyms: ['척추', '디스크', '허리', '추간판', '척추관협착', '요추', '경추', '목디스크', '허리디스크', '골반'],
    no_pay: ['경막외 신경차단(Nerve Block) — 수술 아님', '단순 물리치료', '흡인술', '내시경 척추수술(→ 88-2항 2종)'],
    is_disputed: true,
    sources: ['KB', '흥국생명', 'DB손해보험'],
    notes: '복강경·흉강경은 해당부위 종수 적용. 내시경(카테터)은 88-2항(2종)',
  },
  {
    id: 's-010',
    item_no: '10',
    name: '쇄골·견갑골·늑골·흉골 관혈수술',
    type: 2,
    category: 'musculoskeletal',
    is_cancer: false,
    kcd_codes: ['S22', 'S42.0', 'S42.1'],
    synonyms: ['쇄골', '견갑골', '늑골', '갈비뼈', '흉골', '어깨뼈', '빗장뼈'],
    no_pay: [],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-011-1',
    item_no: '11-1',
    name: '손가락·발가락 절단수술 (골·관절의 이단에 수반하는 것)',
    type: 1,
    category: 'musculoskeletal',
    is_cancer: false,
    kcd_codes: ['S68', 'S98'],
    synonyms: ['손가락절단', '발가락절단', '손가락', '발가락', '절단'],
    no_pay: ['다지증에 대한 절단수술'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-011-2',
    item_no: '11-2',
    name: '기타 사지 절단수술 (다지증 절단 제외)',
    type: 3,
    category: 'musculoskeletal',
    is_cancer: false,
    kcd_codes: ['S48', 'S58', 'S78', 'S88'],
    synonyms: ['사지절단', '팔절단', '다리절단', '절단'],
    no_pay: ['다지증에 대한 절단수술'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-012',
    item_no: '12',
    name: '절단된 사지 재접합수술 (골·관절 이단에 수반하는 것)',
    type: 3,
    category: 'musculoskeletal',
    is_cancer: false,
    kcd_codes: ['S48', 'S58', 'S68', 'S78', 'S88', 'S98'],
    synonyms: ['재접합', '접합술', '사지재접합'],
    no_pay: [],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-013-1',
    item_no: '13-1',
    name: '손가락·발가락의 골 및 관절 관혈수술',
    type: 1,
    category: 'musculoskeletal',
    is_cancer: false,
    kcd_codes: ['S62', 'S92', 'M20'],
    synonyms: ['손가락', '발가락', '손가락관절', '발가락관절', '지골'],
    no_pay: ['발정술(拔釘術) 등 내고정물 제거술', '치과 처치'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-013-2',
    item_no: '13-2',
    name: '기타 사지골·사지관절 관혈수술',
    type: 2,
    category: 'musculoskeletal',
    is_cancer: false,
    kcd_codes: ['M00-M25', 'S40-S99'],
    synonyms: ['무릎', '어깨', '고관절', '관절', '인공관절', '슬관절', '사지', '엉덩이', '팔꿈치', '발목'],
    no_pay: ['발정술(拔釘術) 등 내고정물 제거술', '관절경 단순 세척술(→ 내시경 2종)'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
    notes: '손가락·발가락 관절은 13-1항(1종). 내시경(카테터) 수술은 88-2항(2종)',
  },
  {
    id: 's-014',
    item_no: '14',
    name: '근(筋)·건(腱)·인대·연골 관혈수술',
    type: 1,
    category: 'musculoskeletal',
    is_cancer: false,
    kcd_codes: ['M65-M79', 'S40-S99'],
    synonyms: ['인대', '힘줄', '건', '연골', '근육', '회전근개', '아킬레스건', '십자인대'],
    no_pay: ['단순 봉합술만 시행 시 확인 필요'],
    is_disputed: true,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },

  // ── 호흡기·흉부 ─────────────────────────────────────
  {
    id: 's-015',
    item_no: '15',
    name: '만성부비강염(축농증) 근본수술',
    type: 1,
    category: 'respiratory',
    is_cancer: false,
    kcd_codes: ['J32'],
    synonyms: ['축농증', '부비강', '코', '비염', 'FESS', '부비동', '만성비염', '코막힘'],
    no_pay: ['단순 세척·처치', '외래 항생제 치료만 시행'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-016',
    item_no: '16',
    name: '후두 관혈적 절제수술',
    type: 3,
    category: 'respiratory',
    is_cancer: false,
    kcd_codes: ['J38', 'C32'],
    synonyms: ['후두', '성대', '목', 'larynx', '목소리'],
    no_pay: ['내시경 처치만 시행(→ 88항 적용)'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-017',
    item_no: '17',
    name: '편도·아데노이드 절제수술',
    type: 1,
    category: 'respiratory',
    is_cancer: false,
    kcd_codes: ['J35', 'J35.1', 'J35.2'],
    synonyms: ['편도', '편도선', '아데노이드', '목', 'tonsil', '편도염'],
    no_pay: ['항생제 보존적 치료만 시행'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-018',
    item_no: '18',
    name: '기관·기관지·폐·흉막 관혈수술 (개흉술 수반)',
    type: 4,
    category: 'respiratory',
    is_cancer: false,
    kcd_codes: ['J40-J47', 'J60-J99', 'C34'],
    synonyms: ['기관', '기관지', '폐', '흉막', '개흉', '폐수술'],
    no_pay: ['흉강경 수술은 복강경과 동일하게 해당 부위 종수 적용'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
    notes: '개흉술(Thoracotomy) 수반. 복강경·흉강경은 해당부위 적용',
  },
  {
    id: 's-019',
    item_no: '19',
    name: '폐장 이식수술 (수용자에 한함)',
    type: 5,
    category: 'respiratory',
    is_cancer: false,
    kcd_codes: ['J98.4'],
    synonyms: ['폐이식', '폐장이식', '장기이식'],
    no_pay: ['공여자(Donor)는 해당 없음'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-020',
    item_no: '20',
    name: '흉곽 형성수술',
    type: 3,
    category: 'respiratory',
    is_cancer: false,
    kcd_codes: ['J98', 'Q67'],
    synonyms: ['흉곽', '가슴', '흉곽성형'],
    no_pay: [],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-021',
    item_no: '21',
    name: '종격종양·흉선 절제수술 (개흉술 수반)',
    type: 4,
    category: 'respiratory',
    is_cancer: false,
    kcd_codes: ['D38.3', 'D15.0', 'C37'],
    synonyms: ['종격', '흉선', '흉선암', '종격동'],
    no_pay: [],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },

  // ── 순환기·심장·비장 ──────────────────────────────────
  {
    id: 's-022',
    item_no: '22',
    name: '혈관관혈수술 (하지정맥류·손가락·발가락 제외)',
    type: 3,
    category: 'cardiovascular',
    is_cancer: false,
    kcd_codes: ['I70-I79', 'I80-I89'],
    synonyms: ['혈관', '동맥', '정맥', '혈관수술', '동맥류'],
    no_pay: ['하지정맥류 수술(→ 23번 1종)', '손가락·발가락 혈관(→ 23번 1종)'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-023',
    item_no: '23',
    name: '하지 정맥류 근본수술 및 손가락·발가락 혈관관혈수술',
    type: 1,
    category: 'cardiovascular',
    is_cancer: false,
    kcd_codes: ['I83'],
    synonyms: ['정맥류', '하지', '다리', '종아리', 'varicose'],
    no_pay: ['외모개선 목적만으로 시행되는 경우'],
    is_disputed: true,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-024',
    item_no: '24',
    name: '대동맥·대정맥·폐동맥·관동맥 관혈수술 (개흉술·개복술 수반)',
    type: 5,
    category: 'cardiovascular',
    is_cancer: false,
    kcd_codes: ['I25', 'I71', 'I72', 'I26'],
    synonyms: ['관상동맥', '협심증', 'CABG', '심장', 'bypass', '우회술', '심근경색', '관동맥', '대동맥', 'aorta', '대동맥류'],
    no_pay: ['경피적 관상동맥중재술(PCI·스텐트) → 88항 내시경·경피 3종', '단순 약물치료'],
    is_disputed: true,
    sources: ['KB', '흥국생명', 'DB손해보험'],
    notes: '2대 주요치료비(심장) 특약 별도 확인 필요. 경피적 스텐트 삽입은 88항 적용',
  },
  {
    id: 's-025',
    item_no: '25',
    name: '심막 관혈수술 (개흉술 수반)',
    type: 4,
    category: 'cardiovascular',
    is_cancer: false,
    kcd_codes: ['I30-I32'],
    synonyms: ['심막', '심낭', '심장막'],
    no_pay: [],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-026',
    item_no: '26',
    name: '심장내 관혈수술 (개흉술 수반)',
    type: 5,
    category: 'cardiovascular',
    is_cancer: false,
    kcd_codes: ['I05-I09', 'I34-I39'],
    synonyms: ['심장', '판막', '개흉', '심방', '심실', '심장판막', '판막수술'],
    no_pay: ['개흉술 미수반 경피적 시술(→ 88항 3종)'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-027',
    item_no: '27',
    name: '심장 이식수술 (수용자에 한함)',
    type: 5,
    category: 'cardiovascular',
    is_cancer: false,
    kcd_codes: ['Z94.1'],
    synonyms: ['심장이식', '장기이식', '심장'],
    no_pay: ['공여자(Donor)는 해당 없음'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-028',
    item_no: '28',
    name: '체내용 인공심박조율기 매입술 (Artificial pacemaker)',
    type: 3,
    category: 'cardiovascular',
    is_cancer: false,
    kcd_codes: ['I44-I49', 'Z45.0'],
    synonyms: ['페이스메이커', '심박조율기', '인공심박', 'pacemaker', '부정맥'],
    no_pay: [],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-029',
    item_no: '29',
    name: '비장 절제수술',
    type: 3,
    category: 'cardiovascular',
    is_cancer: false,
    kcd_codes: ['D73', 'S36.0'],
    synonyms: ['비장', '비장절제', '지라'],
    no_pay: [],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },

  // ── 소화기 ────────────────────────────────────────
  {
    id: 's-030',
    item_no: '30',
    name: '이하선 절제수술',
    type: 3,
    category: 'digestive',
    is_cancer: false,
    kcd_codes: ['K11', 'D11'],
    synonyms: ['이하선', '귀밑샘', '침샘', '타액선'],
    no_pay: [],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-031-1',
    item_no: '31-1',
    name: '악하선·설하선 절제수술',
    type: 2,
    category: 'digestive',
    is_cancer: false,
    kcd_codes: ['K11', 'D11'],
    synonyms: ['악하선', '설하선', '침샘', '타액선'],
    no_pay: ['타석제거'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-031-2',
    item_no: '31-2',
    name: '기타 타액선 절제수술 (타석제거 제외)',
    type: 1,
    category: 'digestive',
    is_cancer: false,
    kcd_codes: ['K11'],
    synonyms: ['타액선', '침샘'],
    no_pay: ['타석제거'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-032',
    item_no: '32',
    name: '식도 이단술 (개흉술·개복술 수반)',
    type: 4,
    category: 'digestive',
    is_cancer: false,
    kcd_codes: ['K22', 'C15'],
    synonyms: ['식도', '식도수술', '식도암'],
    no_pay: [],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-033',
    item_no: '33',
    name: '위 절제수술 Gastrectomy (개복술 수반)',
    type: 4,
    category: 'digestive',
    is_cancer: false,
    kcd_codes: ['K25-K31', 'C16'],
    synonyms: ['위', 'stomach', '위암', '위절제', '위궤양', '소화', '복강경'],
    no_pay: ['단순 내시경 지혈술', '약물치료'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
    notes: '복강경·흉강경 수술은 해당 부위 종수 적용',
  },
  {
    id: 's-034',
    item_no: '34',
    name: '기타 위·식도 관혈수술 (개흉술·개복술 수반)',
    type: 3,
    category: 'digestive',
    is_cancer: false,
    kcd_codes: ['K22', 'K25-K31'],
    synonyms: ['위', '식도', '위수술'],
    no_pay: [],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-035',
    item_no: '35',
    name: '간장·췌장 관혈수술 (개복술 수반)',
    type: 4,
    category: 'digestive',
    is_cancer: false,
    kcd_codes: ['K70-K78', 'K86', 'C22', 'C25'],
    synonyms: ['간', 'liver', '췌장', '간경화', '간암', '지방간', '췌장염', '간절제'],
    no_pay: ['간생검(조직검사 목적)', '천자 배액술'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-036',
    item_no: '36',
    name: '담낭·담도 관혈수술 (개복술 수반)',
    type: 3,
    category: 'digestive',
    is_cancer: false,
    kcd_codes: ['K80-K83', 'C23', 'C24'],
    synonyms: ['담낭', '쓸개', '담석', '담도', 'gallbladder', '복강경'],
    no_pay: ['체외충격파 담석 쇄석술(→ 87항 2종)', 'ERCP 단순 진단'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
    notes: '복강경 담낭절제술도 해당 부위(담낭·담도) 3종 적용',
  },
  {
    id: 's-037',
    item_no: '37',
    name: '간장 이식수술 (수용자에 한함, 개복술 수반)',
    type: 5,
    category: 'digestive',
    is_cancer: false,
    kcd_codes: ['K72', 'Z94.4'],
    synonyms: ['간이식', '장기이식', '간'],
    no_pay: ['공여자(Donor)는 해당 없음'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-038',
    item_no: '38',
    name: '췌장 이식수술 (수용자에 한함, 개복술 수반, 랑게르한스 소도 이식 제외)',
    type: 5,
    category: 'digestive',
    is_cancer: false,
    kcd_codes: ['E13', 'Z94.8'],
    synonyms: ['췌장이식', '장기이식', '췌장'],
    no_pay: ['랑게르한스 소도(Islet of Langerhans) 세포 이식수술', '공여자(Donor)'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-039',
    item_no: '39',
    name: '탈장 근본수술',
    type: 1,
    category: 'digestive',
    is_cancer: false,
    kcd_codes: ['K40-K46'],
    synonyms: ['탈장', '서혜부', 'hernia', '복벽탈장', '배꼽탈장'],
    no_pay: ['흡인·천자술'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-040',
    item_no: '40',
    name: '전신성 복막염 수술',
    type: 2,
    category: 'digestive',
    is_cancer: false,
    kcd_codes: ['K65'],
    synonyms: ['복막염', '복막', '전신성복막염'],
    no_pay: [],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-041',
    item_no: '41',
    name: '충수절제술 (충수염·충수주위 농양수술·국한성 복막염 포함), 맹장봉축술',
    type: 2,
    category: 'digestive',
    is_cancer: false,
    kcd_codes: ['K35-K37'],
    synonyms: ['맹장', '충수', '맹장염', 'appendix', '충수염', '충수절제'],
    no_pay: ['단순 보존적 항생제 치료만 시행'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-042',
    item_no: '42',
    name: '직장탈 근본수술',
    type: 1,
    category: 'digestive',
    is_cancer: false,
    kcd_codes: ['K62.3'],
    synonyms: ['직장탈', '탈항', '항문'],
    no_pay: [],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-043',
    item_no: '43',
    name: '소장·결장·직장·장간막 관혈수술 (개복술 수반, 직장탈 제외)',
    type: 4,
    category: 'digestive',
    is_cancer: false,
    kcd_codes: ['K56-K63', 'C18-C20'],
    synonyms: ['소장', '결장', '직장', '대장', '장', 'colon', '직장암', '대장암', '장간막'],
    no_pay: ['단순 내시경 처치', '직장탈 근본수술(→ 42번 1종)'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
    notes: '복강경도 해당 부위 4종 적용',
  },
  {
    id: 's-044',
    item_no: '44',
    name: '치루·탈항·치핵 근본수술 (근치를 목적으로 하지 않는 수술 제외)',
    type: 1,
    category: 'digestive',
    is_cancer: false,
    kcd_codes: ['K64', 'K60'],
    synonyms: ['치핵', '치질', '항문', 'hemorrhoid', '탈항', '치루'],
    no_pay: ['단순 고무링 결찰술(외래 처치)', '약물 주입만 시행', '근치 목적 아닌 단순 처치'],
    is_disputed: true,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },

  // ── 비뇨·생식기 ──────────────────────────────────────
  {
    id: 's-045',
    item_no: '45',
    name: '신장·방광·신우·요관 관혈수술 (개복술 수반, 경요도적 조작·방광류·요실금 교정 제외)',
    type: 4,
    category: 'urogenital',
    is_cancer: false,
    kcd_codes: ['N20-N39', 'C64-C67'],
    synonyms: ['신장', '방광', '요관', '신우', 'kidney', '소변', '비뇨기', '신장암'],
    no_pay: ['경요도적 내시경 처치(→ 88-3항 1종)', '천자 배액'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-046',
    item_no: '46',
    name: '요도 관혈수술 (경요도적 조작 제외)',
    type: 2,
    category: 'urogenital',
    is_cancer: false,
    kcd_codes: ['N35', 'N36'],
    synonyms: ['요도', '요도수술'],
    no_pay: ['경요도적 조작'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-047',
    item_no: '47',
    name: '방광류·요실금 교정수술',
    type: 1,
    category: 'urogenital',
    is_cancer: false,
    kcd_codes: ['N39.3', 'N39.4', 'N81'],
    synonyms: ['요실금', '방광류', '요실금수술'],
    no_pay: [],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
    notes: 'DB손해보험 약관에서 요실금(N39.3, N39.4, R32)은 질병수술비 면책 확인 필요',
    type_by_company: { 'DB손해보험': 1 },
  },
  {
    id: 's-048',
    item_no: '48',
    name: '신장 이식수술 (수용자에 한함)',
    type: 5,
    category: 'urogenital',
    is_cancer: false,
    kcd_codes: ['Z94.0'],
    synonyms: ['신장이식', '장기이식', '신장'],
    no_pay: ['공여자(Donor)는 해당 없음'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-049',
    item_no: '49',
    name: '음경 절단수술 (포경수술·음경이물제거수술 제외)',
    type: 3,
    category: 'urogenital',
    is_cancer: false,
    kcd_codes: ['C60', 'N48'],
    synonyms: ['음경', '음경절단'],
    no_pay: ['포경수술', '음경이물제거수술'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-050',
    item_no: '50',
    name: '고환·부고환·정관·정색·정낭 관혈수술, 전립선 관혈수술',
    type: 2,
    category: 'urogenital',
    is_cancer: false,
    kcd_codes: ['C61', 'N40-N43', 'N45-N46'],
    synonyms: ['고환', '전립선', '부고환', '정관', '남성'],
    no_pay: ['불임수술', '불임복원술'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-051',
    item_no: '51',
    name: '음낭관혈수술',
    type: 1,
    category: 'urogenital',
    is_cancer: false,
    kcd_codes: ['N50'],
    synonyms: ['음낭', '음낭수술'],
    no_pay: [],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-052',
    item_no: '52',
    name: '자궁·난소·난관 관혈수술 (제왕절개·경질적 조작 제외)',
    type: 2,
    category: 'urogenital',
    is_cancer: false,
    kcd_codes: ['N80-N99', 'C51-C57'],
    synonyms: ['자궁', '난소', '난관', '자궁근종', '생리', '자궁내막증', '여성', '자궁경부'],
    no_pay: ['경질적 수술(→ 53번 1종)', '제왕절개(→ 54번 1종)', '인공임신중절술'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
    notes: '복강경은 해당 부위 2종 적용',
  },
  {
    id: 's-053',
    item_no: '53',
    name: '경질적 자궁·난소·난관 수술',
    type: 1,
    category: 'urogenital',
    is_cancer: false,
    kcd_codes: ['N80-N99'],
    synonyms: ['자궁', '경질', '여성', '질식수술'],
    no_pay: [],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
    notes: '수술개시일부터 60일 이내 2회 이상은 1회로 간주',
  },
  {
    id: 's-054',
    item_no: '54',
    name: '제왕절개만출술 (帝王切開娩出術)',
    type: 1,
    category: 'urogenital',
    is_cancer: false,
    kcd_codes: ['O82'],
    synonyms: ['제왕절개', '출산', '분만', '임신', '제왕', 'CS', '산부인과'],
    no_pay: ['질병수술비 특약 — 임신·출산 관련 수술 제외조항 해당 시 부지급 가능'],
    is_disputed: true,
    sources: ['KB', '흥국생명', 'DB손해보험'],
    notes: '⚠️ 질병수술비 특약에서 임신·출산(O00-O99) 제외 여부 반드시 확인',
  },
  {
    id: 's-055',
    item_no: '55',
    name: '질탈 근본수술',
    type: 1,
    category: 'urogenital',
    is_cancer: false,
    kcd_codes: ['N81'],
    synonyms: ['질탈', '자궁탈출', '여성'],
    no_pay: [],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },

  // ── 내분비 ────────────────────────────────────────
  {
    id: 's-056',
    item_no: '56',
    name: '뇌하수체종양 절제수술',
    type: 5,
    category: 'endocrine',
    is_cancer: false,
    kcd_codes: ['D35.2', 'C75.1'],
    synonyms: ['뇌하수체', '뇌종양', '두개', '내분비', '뇌'],
    no_pay: ['방사선 치료만 시행(→ 방사선 분류표 3종)'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-057',
    item_no: '57',
    name: '갑상선·부갑상선 관혈수술',
    type: 3,
    category: 'endocrine',
    is_cancer: false,
    kcd_codes: ['C73', 'E04-E07', 'D34'],
    synonyms: ['갑상선', '갑상샘', '부갑상선', 'thyroid', '목', '내분비', '갑상선암'],
    no_pay: ['단순 미세침 흡인검사(세포검사)는 수술 아님', '약물치료'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
    notes: '갑상선암에 대한 근치적 절제술 → 암 수술 5종(암 특약 별도). 내시경·복강경 포함',
  },
  {
    id: 's-058',
    item_no: '58',
    name: '부신 절제수술',
    type: 4,
    category: 'endocrine',
    is_cancer: false,
    kcd_codes: ['E27', 'C74'],
    synonyms: ['부신', 'adrenal', '내분비', '호르몬'],
    no_pay: ['천자 생검'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },

  // ── 신경계 ────────────────────────────────────────
  {
    id: 's-059',
    item_no: '59',
    name: '두개내 관혈수술 (개두술 수반)',
    type: 5,
    category: 'neurological',
    is_cancer: false,
    kcd_codes: ['I60-I69', 'G00-G09', 'C71', 'D33'],
    synonyms: ['뇌', '두개', '뇌출혈', '뇌종양', '뇌경색', '개두술', '뇌수술', '뇌졸중', 'stroke', '뇌혈관'],
    no_pay: ['감마나이프·사이버나이프 단독(→ 방사선 분류표 3종)', '천자 배액만 시행'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
    notes: '감마나이프·사이버나이프 등 정위적 방사선치료 → 방사선 분류표 3종',
  },
  {
    id: 's-060',
    item_no: '60',
    name: '신경 관혈수술',
    type: 2,
    category: 'neurological',
    is_cancer: false,
    kcd_codes: ['G50-G59'],
    synonyms: ['신경', '손목', '터널', '손목터널', 'carpal', '저림', '마비', '손저림', '말초신경'],
    no_pay: ['신경차단(Nerve Block) — 수술로 인정하지 않음', '단순 주사 치료'],
    is_disputed: true,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-061',
    item_no: '61',
    name: '관혈적 척수종양 절제수술',
    type: 4,
    category: 'neurological',
    is_cancer: false,
    kcd_codes: ['D32', 'D33', 'G95'],
    synonyms: ['척수', '척수종양', '척수수술'],
    no_pay: [],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-062',
    item_no: '62',
    name: '척수경막내외 관혈수술',
    type: 3,
    category: 'neurological',
    is_cancer: false,
    kcd_codes: ['G96', 'G97'],
    synonyms: ['척수경막', '척수', '경막'],
    no_pay: [],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },

  // ── 시각기 ────────────────────────────────────────
  {
    id: 's-063',
    item_no: '63',
    name: '안검하수증 수술 (안검내반증 제외)',
    type: 1,
    category: 'eye',
    is_cancer: false,
    kcd_codes: ['H02.0'],
    synonyms: ['안검하수', '눈꺼풀처짐', '눈꺼풀', '안검', '눈'],
    no_pay: ['외모개선 목적 쌍꺼풀수술', '안검내반증'],
    is_disputed: true,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-064',
    item_no: '64',
    name: '누소관 형성수술 (누관튜브삽입술 포함)',
    type: 1,
    category: 'eye',
    is_cancer: false,
    kcd_codes: ['H04'],
    synonyms: ['누소관', '눈물관', '누관', '눈물'],
    no_pay: [],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-065',
    item_no: '65',
    name: '누낭비강 관혈수술',
    type: 2,
    category: 'eye',
    is_cancer: false,
    kcd_codes: ['H04.3'],
    synonyms: ['누낭', '눈물낭', '누낭비강'],
    no_pay: [],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-066',
    item_no: '66',
    name: '결막낭 형성수술',
    type: 2,
    category: 'eye',
    is_cancer: false,
    kcd_codes: ['H11'],
    synonyms: ['결막', '결막낭', '눈'],
    no_pay: [],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-067',
    item_no: '67',
    name: '각막·결막·공막 봉합수술',
    type: 1,
    category: 'eye',
    is_cancer: false,
    kcd_codes: ['H16', 'H11', 'H15'],
    synonyms: ['각막', '결막', '공막', '봉합', '눈'],
    no_pay: [],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-068',
    item_no: '68',
    name: '각막·공막 이식수술',
    type: 2,
    category: 'eye',
    is_cancer: false,
    kcd_codes: ['H17-H18', 'H15'],
    synonyms: ['각막이식', '공막이식', '각막', '공막', '눈', 'keratoplasty'],
    no_pay: ['단순 봉합술만 시행'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-069',
    item_no: '69',
    name: '전방·홍채·유리체 관혈수술',
    type: 2,
    category: 'eye',
    is_cancer: false,
    kcd_codes: ['H21', 'H43-H44'],
    synonyms: ['전방', '홍채', '유리체', '눈', '안과'],
    no_pay: ['약물주입술'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-070',
    item_no: '70',
    name: '녹내장 관혈수술',
    type: 3,
    category: 'eye',
    is_cancer: false,
    kcd_codes: ['H40'],
    synonyms: ['녹내장', '눈압', '안압', '눈', '안과', '섬유주절제'],
    no_pay: ['레이저 단독(→ 88항 1종 적용)', '안압하강제 약물치료'],
    is_disputed: true,
    sources: ['KB', '흥국생명', 'DB손해보험'],
    notes: '레이저 섬유주성형술(ALT/SLT) 등 레이저 단독은 73번(1종) 적용',
  },
  {
    id: 's-071',
    item_no: '71',
    name: '백내장·수정체 관혈수술',
    type: 1,
    category: 'eye',
    is_cancer: false,
    kcd_codes: ['H25', 'H26'],
    synonyms: ['백내장', '수정체', 'phaco', '눈', '안과', '시력'],
    no_pay: ['안경·콘택트렌즈 대체 시력교정술(라식·라섹)', '단순 약물주입술'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-072',
    item_no: '72',
    name: '망막박리 수술',
    type: 2,
    category: 'eye',
    is_cancer: false,
    kcd_codes: ['H33'],
    synonyms: ['망막박리', '망막', '유리체', '눈', '안과', '시력저하'],
    no_pay: ['레이저 광응고술만 단독 시행(→ 73번 1종)'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
    notes: '수술개시일부터 60일 이내 2회 이상은 1회로 간주',
  },
  {
    id: 's-073',
    item_no: '73',
    name: '레이저에 의한 안구수술 (시력회복·시력개선 목적 제외)',
    type: 1,
    category: 'eye',
    is_cancer: false,
    kcd_codes: ['H33-H36'],
    synonyms: ['레이저', '눈', '망막', '당뇨망막', '안과', '레이저안구'],
    no_pay: ['미용·시력교정 목적 라식·라섹', '다래끼·콩다래끼 레이저', '시력회복·시력개선 목적'],
    is_disputed: true,
    sources: ['KB', '흥국생명', 'DB손해보험'],
    notes: '치료목적 레이저만 해당. 60일 이내 2회 이상은 1회로 간주',
  },
  {
    id: 's-074',
    item_no: '74',
    name: '냉동응고에 의한 안구수술',
    type: 2,
    category: 'eye',
    is_cancer: false,
    kcd_codes: ['H33-H36'],
    synonyms: ['냉동응고', '안구', '눈', '안과', '망막'],
    no_pay: [],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
    notes: '60일 이내 2회 이상은 1회로 간주',
  },
  {
    id: 's-075',
    item_no: '75',
    name: '안구적출술·조직충전술',
    type: 3,
    category: 'eye',
    is_cancer: false,
    kcd_codes: ['H44', 'Z96.1'],
    synonyms: ['안구적출', '눈적출', '의안', '눈'],
    no_pay: [],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-076',
    item_no: '76',
    name: '안와내종양절제수술',
    type: 3,
    category: 'eye',
    is_cancer: false,
    kcd_codes: ['D31', 'H05'],
    synonyms: ['안와', '눈', '안와종양'],
    no_pay: [],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-077',
    item_no: '77',
    name: '관혈적 안와내 이물제거수술',
    type: 1,
    category: 'eye',
    is_cancer: false,
    kcd_codes: ['H05', 'S05'],
    synonyms: ['안와', '이물', '눈', '이물제거'],
    no_pay: [],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-078',
    item_no: '78',
    name: '안근 관혈수술',
    type: 1,
    category: 'eye',
    is_cancer: false,
    kcd_codes: ['H49-H50'],
    synonyms: ['안근', '사시', '눈', '안근수술'],
    no_pay: [],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },

  // ── 청각기 ────────────────────────────────────────
  {
    id: 's-079',
    item_no: '79',
    name: '관혈적 고막 성형술 (고막 패치술 제외)',
    type: 2,
    category: 'ear',
    is_cancer: false,
    kcd_codes: ['H72', 'H73'],
    synonyms: ['고막', '귀', '고막성형', '중이'],
    no_pay: ['고막 패치술'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-080',
    item_no: '80',
    name: '유양동 절제술 (mastoidectomy)',
    type: 2,
    category: 'ear',
    is_cancer: false,
    kcd_codes: ['H70'],
    synonyms: ['유양동', '귀', '유양돌기', '중이염'],
    no_pay: [],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-081',
    item_no: '81',
    name: '중이 관혈수술 (중이내 튜브유치술 제외)',
    type: 2,
    category: 'ear',
    is_cancer: false,
    kcd_codes: ['H65-H75'],
    synonyms: ['중이', '귀', '중이염', '고막'],
    no_pay: ['중이내 튜브유치술(→ 82번 1종)'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-082',
    item_no: '82',
    name: '중이내 튜브유치술 (고막 패치술 제외)',
    type: 1,
    category: 'ear',
    is_cancer: false,
    kcd_codes: ['H65', 'H66'],
    synonyms: ['튜브유치', '중이', '귀', '삼출성중이염', '튜브삽입'],
    no_pay: ['고막 패치술'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
    notes: '60일 이내 2회 이상은 1회로 간주',
  },
  {
    id: 's-083',
    item_no: '83',
    name: '내이 관혈수술',
    type: 3,
    category: 'ear',
    is_cancer: false,
    kcd_codes: ['H80-H83'],
    synonyms: ['내이', '귀', '내이수술', '와우', '달팽이관'],
    no_pay: [],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },

  // ── 기타 ──────────────────────────────────────────
  {
    id: 's-084',
    item_no: '84',
    name: '상기 이외의 개두술 (開頭術)',
    type: 3,
    category: 'other',
    is_cancer: false,
    kcd_codes: [],
    synonyms: ['개두술', '뇌수술', '두개골'],
    no_pay: [],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-085',
    item_no: '85',
    name: '상기 이외의 개흉술 (開胸術)',
    type: 3,
    category: 'other',
    is_cancer: false,
    kcd_codes: [],
    synonyms: ['개흉술', '흉부수술', '가슴수술'],
    no_pay: [],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-086',
    item_no: '86',
    name: '상기 이외의 개복술 (開腹術)',
    type: 2,
    category: 'other',
    is_cancer: false,
    kcd_codes: [],
    synonyms: ['개복술', '복부수술', '배수술'],
    no_pay: [],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
  },
  {
    id: 's-087',
    item_no: '87',
    name: '체외충격파쇄석술 (E.S.W.L) — 체외충격파치료술(E.S.W.T) 제외',
    type: 2,
    category: 'other',
    is_cancer: false,
    kcd_codes: ['N20', 'N21', 'K80'],
    synonyms: ['쇄석술', '결석', '요로결석', '담석', 'ESWL', '체외충격파'],
    no_pay: ['체외충격파치료술(E.S.W.T) — 근골격 치료 목적'],
    is_disputed: true,
    sources: ['KB', '흥국생명', 'DB손해보험'],
    notes: '60일 이내 2회 이상은 1회로 간주',
  },

  // ── 내시경·경피적 수술 (88항) ─────────────────────────
  {
    id: 's-088-1',
    item_no: '88-1',
    name: '내시경·카테터·고주파 전극에 의한 경피적 수술 — 뇌, 심장',
    type: 3,
    category: 'other',
    is_cancer: false,
    kcd_codes: ['I60-I69', 'I20-I25', 'C71', 'G00'],
    synonyms: ['내시경', '경피적', '카테터', '고주파', '뇌', '심장', '심방세동'],
    no_pay: ['흡인·천자술', '약물주입요법', '검사 목적'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
    notes: '복강경·흉강경에 의한 수술은 해당 부위(1~87항)의 수술로 적용',
  },
  {
    id: 's-088-2',
    item_no: '88-2',
    name: '내시경·카테터·고주파 전극에 의한 경피적 수술 — 후두, 흉부장기(심장 제외), 복부장기(비뇨·생식기 제외), 척추, 사지관절(손가락·발가락 제외)',
    type: 2,
    category: 'other',
    is_cancer: false,
    kcd_codes: ['M40-M54', 'K00-K93', 'J38', 'M16-M17'],
    synonyms: ['내시경', '경피적', '척추내시경', '복강경', '관절경', '디스크', '추간판', '무릎', '어깨', '후두'],
    no_pay: ['흡인·천자술', '약물주입요법', '검사 목적', '복강경·흉강경(→ 해당 부위 종수)'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
    notes: '복강경·흉강경에 의한 수술은 해당 부위(1~87항)의 수술로 적용',
  },
  {
    id: 's-088-3',
    item_no: '88-3',
    name: '내시경·카테터·고주파 전극에 의한 경피적 수술 — 비뇨·생식기 및 손가락·발가락',
    type: 1,
    category: 'other',
    is_cancer: false,
    kcd_codes: ['N20-N39', 'K63.5', 'S60-S69', 'S90-S99'],
    synonyms: ['경요도', '내시경', '요로결석', '대장용종', '용종', 'EMR', 'ESD', '손가락', '발가락', '비뇨기', '폴립', 'polyp'],
    no_pay: ['흡인·천자술', '약물주입요법', '검사 목적'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
    notes: '⚠️ 대장용종(K63.5) 내시경 절제술은 이 항목(88-3, 1종) 적용. 60일 이내 2회 이상은 1회로 간주',
  },

  // ══════════════════════════════════════════════════
  // Ⅱ. 악성신생물(암) 치료 목적의 수술
  // ══════════════════════════════════════════════════

  {
    id: 'c-001',
    item_no: 'Ⅱ-1',
    name: '관혈적 악성신생물 근치수술 (Radical curative surgery, C44 제외)',
    type: 5,
    category: 'cancer',
    is_cancer: true,
    kcd_codes: ['C00-C97'],
    synonyms: ['암', '악성', '종양', 'cancer', '근치', '악성신생물', '암절제', '암수술', '암근치'],
    no_pay: [
      '내시경·경피적 암수술(→ Ⅱ-2항 3종)',
      '항암방사선·항암약물치료는 수술비 미지급',
      '흡인·천자술',
      '기타피부암(C44) → Ⅱ-1-1항 3종',
    ],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
    notes: '암 특약(암수술비) 별도 지급 가능. 비고형암 비관혈적 근치술도 5종 준용',
  },
  {
    id: 'c-001-1',
    item_no: 'Ⅱ-1-1',
    name: '기타피부암(C44) 수술',
    type: 3,
    category: 'cancer',
    is_cancer: true,
    kcd_codes: ['C44'],
    synonyms: ['피부암', 'C44', '피부', '기저세포암', '편평세포암', '기타피부암'],
    no_pay: ['미용 목적 피부병변 제거'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
    notes: '관혈적 수술도 3종 (일반 암 근치수술 5종과 구분)',
  },
  {
    id: 'c-002',
    item_no: 'Ⅱ-2',
    name: '내시경·카테터·고주파 전극에 의한 악성신생물 수술',
    type: 3,
    category: 'cancer',
    is_cancer: true,
    kcd_codes: ['C00-C97'],
    synonyms: ['암', '내시경', '경피', '고주파', 'RFA', '악성', '암내시경'],
    no_pay: ['흡인·천자·약물주입만 시행', '항암제 투여 목적 중심정맥삽관술 단독'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
    notes: '60일 이내 재수술 1회 간주',
  },
  {
    id: 'c-003',
    item_no: 'Ⅱ-3',
    name: '상기 이외의 기타 악성신생물 수술',
    type: 3,
    category: 'cancer',
    is_cancer: true,
    kcd_codes: ['C00-C97'],
    synonyms: ['암', '악성신생물', '기타암수술'],
    no_pay: ['흡인·천자술', '약물주입요법'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
    notes: '60일 이내 2회 이상은 1회로 간주',
  },
  {
    id: 'c-bm',
    item_no: 'Ⅱ-특',
    name: '조혈모세포(골수) 이식술 — 비고형암 비관혈적 근치술 (5종 준용)',
    type: 5,
    category: 'cancer',
    is_cancer: true,
    kcd_codes: ['C81-C96', 'C91-C95'],
    synonyms: ['골수이식', '혈액암', '백혈병', '림프종', '조혈모세포', '이식', '골수', '다발성골수종'],
    no_pay: ['약물 투여 목적 중심정맥삽관술만 단독 시행 시 5종 불인정'],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
    notes: '추출·필터링·배양·제거·주입 전 과정 포함하여 1회 수술로 인정',
  },

  // ══════════════════════════════════════════════════
  // Ⅲ. 악성신생물 근치·두개내신생물 근치 방사선 조사
  // ══════════════════════════════════════════════════

  {
    id: 'r-001',
    item_no: 'Ⅲ-1',
    name: '악성신생물 근치 방사선 조사 (5,000Rad 이상, 사이버나이프 포함)',
    type: 3,
    category: 'cancer',
    is_cancer: true,
    kcd_codes: ['C00-C97'],
    synonyms: ['방사선', '사이버나이프', '감마나이프', '암', '방사선치료', 'Rad', 'cyberknife', '정위적방사선', '방사선조사'],
    no_pay: ['5,000Rad 미만 완화적 방사선치료', '항암약물치료'],
    is_disputed: true,
    sources: ['KB', '흥국생명', 'DB손해보험'],
    notes: '재해·질병수술비 특약에서 방사선 치료가 수술로 인정되는지 약관 별도 확인 필요',
  },
  {
    id: 'r-002',
    item_no: 'Ⅲ-2',
    name: '두개내 신생물 근치 감마나이프 (Gammaknife) 정위적 방사선 치료',
    type: 3,
    category: 'cancer',
    is_cancer: true,
    kcd_codes: ['C71', 'D33', 'C72'],
    synonyms: ['감마나이프', '뇌종양', '두개내', '뇌', '정위적방사선'],
    no_pay: [],
    is_disputed: false,
    sources: ['KB', '흥국생명', 'DB손해보험'],
    notes: '60일 이내 2회 이상은 1회로 간주',
  },
]

// 부위 카테고리 한국어 라벨
export const CATEGORY_LABELS: Record<string, string> = {
  skin_breast: '피부·유방',
  musculoskeletal: '근골격',
  respiratory: '호흡기·흉부',
  cardiovascular: '순환기·심장',
  digestive: '소화기',
  urogenital: '비뇨·생식기',
  endocrine: '내분비',
  neurological: '신경계',
  eye: '시각기 (눈)',
  ear: '청각기 (귀)',
  other: '기타',
  cancer: '암 수술',
}

// 종별 배율 (배율 방식 사용 시)
export const TYPE_MULTIPLIER: Record<number, number> = {
  1: 1,
  2: 2,
  3: 5,
  4: 10,
  5: 20,
}